import { describe, expect, it, beforeEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  ATTACHMENT_ONLY,
  dedupKey,
  finalUsageByKey,
  firstTimestamp,
  getReadErrors,
  isBillable,
  isRealPrompt,
  promptTextOf,
  readLines,
  resetReadErrors,
  snippet,
  textOf,
} from '../src/parser.js';

const tmp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'aita-parser-'));
const writeJsonl = (dir, name, lines) => {
  const file = path.join(dir, name);
  fs.writeFileSync(file, lines.map((l) => (typeof l === 'string' ? l : JSON.stringify(l))).join('\n'));
  return file;
};

const userLine = (content, extra = {}) => ({ type: 'user', message: { content }, uuid: 'u1', ...extra });

describe('textOf', () => {
  it('returns plain string content unchanged', () => {
    expect(textOf('hello')).toBe('hello');
  });

  it('joins text blocks with newlines', () => {
    expect(textOf([{ type: 'text', text: 'a' }, { type: 'text', text: 'b' }])).toBe('a\nb');
  });

  it('rejects any content carrying a tool_result — that is an agent loop, not a prompt', () => {
    expect(textOf([{ type: 'tool_result' }, { type: 'text', text: 'ignored' }])).toBeNull();
  });

  it('labels attachment-only prompts so their turn still gets attributed', () => {
    expect(textOf([{ type: 'image' }])).toBe(ATTACHMENT_ONLY);
    expect(textOf([{ type: 'document' }])).toBe(ATTACHMENT_ONLY);
  });

  it('prefers real text over the attachment label when both are present', () => {
    expect(textOf([{ type: 'image' }, { type: 'text', text: 'look' }])).toBe('look');
  });

  it('returns null for non-array, non-string and empty content', () => {
    expect(textOf(null)).toBeNull();
    expect(textOf(undefined)).toBeNull();
    expect(textOf({ type: 'text' })).toBeNull();
    expect(textOf([])).toBeNull();
    expect(textOf([{ type: 'thinking' }])).toBeNull();
  });

  it('ignores text blocks whose text is not a string', () => {
    expect(textOf([{ type: 'text', text: 42 }])).toBeNull();
  });

  it('returns whitespace-only string content as-is (trimming is the caller job)', () => {
    expect(textOf('   ')).toBe('   ');
  });
});

describe('isRealPrompt', () => {
  it('accepts a typed prompt', () => {
    expect(isRealPrompt(userLine('do the thing'))).toBe(true);
  });

  it('rejects non-user lines and nullish input', () => {
    expect(isRealPrompt({ type: 'assistant', message: { content: 'hi' } })).toBe(false);
    expect(isRealPrompt(null)).toBe(false);
    expect(isRealPrompt(undefined)).toBe(false);
  });

  it('rejects meta and sidechain lines', () => {
    expect(isRealPrompt(userLine('x', { isMeta: true }))).toBe(false);
    expect(isRealPrompt(userLine('x', { isSidechain: true }))).toBe(false);
  });

  it('rejects every machine-generated noise prefix', () => {
    const prefixes = [
      '<local-command-caveat>',
      '<local-command-stdout>',
      '<local-command-stderr>',
      '<command-args>',
      '<task-notification>',
      '<system-reminder>',
      '<user-prompt-submit-hook>',
      '<ide_opened_file>',
      '<ide_selection>',
      '<ide_diagnostics>',
      'Caveat: The messages below were generated by the user while running local commands',
      'This session is being continued from a previous conversation',
    ];
    for (const p of prefixes) {
      expect(isRealPrompt(userLine(p + ' tail')), p).toBe(false);
    }
  });

  it('rejects blank and whitespace-only prompts', () => {
    expect(isRealPrompt(userLine(''))).toBe(false);
    expect(isRealPrompt(userLine('   \n  '))).toBe(false);
  });

  it('keeps a slash command that carries arguments — a real action that costs money', () => {
    const t = '<command-name>/goal</command-name>\n<command-args>ship it</command-args>';
    expect(isRealPrompt(userLine(t))).toBe(true);
  });

  it('keeps a skill command with no args tag at all', () => {
    // <command-message> form: the args tag is present only when args were passed.
    const t = '<command-message>code-review</command-message>\n<command-name>/code-review</command-name>';
    expect(isRealPrompt(userLine(t))).toBe(true);
  });

  it('drops a no-op settings command: args tag present but empty', () => {
    const t = '<command-name>/clear</command-name>\n<command-args></command-args>';
    expect(isRealPrompt(userLine(t))).toBe(false);
  });

  it('drops malformed command plumbing that has no command-name', () => {
    expect(isRealPrompt(userLine('<command-message>orphan</command-message>'))).toBe(false);
  });
});

describe('promptTextOf', () => {
  it('renders a command as name + args, never the raw XML blob', () => {
    const t = '<command-name>/goal</command-name>\n<command-args>increase font zoom</command-args>';
    expect(promptTextOf(userLine(t))).toBe('/goal increase font zoom');
  });

  it('renders an argless command as just its name', () => {
    const t = '<command-message>x</command-message>\n<command-name>/code-review</command-name>';
    expect(promptTextOf(userLine(t))).toBe('/code-review');
  });

  it('returns a plain prompt trimmed', () => {
    expect(promptTextOf(userLine('  hello  '))).toBe('hello');
  });

  it('returns an empty string when there is no content', () => {
    expect(promptTextOf({ type: 'user', message: {} })).toBe('');
  });
});

describe('isBillable', () => {
  const line = (over = {}) => ({ type: 'assistant', message: { model: 'm', usage: {}, ...over } });

  it('accepts an assistant line with a model and a usage record', () => {
    expect(isBillable(line())).toBe(true);
  });

  it('rejects the synthetic model', () => {
    expect(isBillable(line({ model: '<synthetic>' }))).toBe(false);
  });

  it('rejects a missing model or missing usage', () => {
    expect(isBillable(line({ model: undefined }))).toBe(false);
    expect(isBillable(line({ usage: undefined }))).toBe(false);
    expect(isBillable(line({ usage: null }))).toBe(false);
  });

  it('rejects user lines and nullish input', () => {
    expect(isBillable({ type: 'user', message: { model: 'm', usage: {} } })).toBe(false);
    expect(isBillable(null)).toBe(false);
  });
});

describe('dedupKey', () => {
  it('keys on id|requestId when both are present', () => {
    expect(dedupKey({ message: { id: 'msg_1' }, requestId: 'req_1', uuid: 'u' })).toBe('msg_1|req_1');
  });

  it('falls back to uuid when either half is missing', () => {
    expect(dedupKey({ message: { id: 'msg_1' }, uuid: 'u' })).toBe('uuid:u');
    expect(dedupKey({ requestId: 'req_1', uuid: 'u' })).toBe('uuid:u');
    expect(dedupKey({ uuid: 'u' })).toBe('uuid:u');
  });
});

describe('finalUsageByKey', () => {
  const streamed = (out) => ({
    type: 'assistant',
    requestId: 'r1',
    uuid: 'u1',
    message: { id: 'm1', model: 'claude-opus-5', usage: { output_tokens: out } },
  });

  it('keeps the LAST usage for a streamed message, not the first', () => {
    const map = finalUsageByKey([streamed(3), streamed(3), streamed(276)]);
    expect(map.size).toBe(1);
    expect(map.get('m1|r1').output_tokens).toBe(276);
  });

  it('skips non-billable lines entirely', () => {
    expect(finalUsageByKey([{ type: 'user', message: { content: 'x' } }]).size).toBe(0);
  });

  it('returns an empty map for no lines', () => {
    expect(finalUsageByKey([]).size).toBe(0);
  });
});

describe('snippet', () => {
  it('collapses all whitespace runs to single spaces and trims', () => {
    expect(snippet('  a\n\n b\t\tc  ')).toBe('a b c');
  });

  it('leaves text at or under the limit untouched', () => {
    expect(snippet('abcde', 5)).toBe('abcde');
  });

  it('truncates with an ellipsis past the limit', () => {
    expect(snippet('abcdef', 5)).toBe('abcde…');
  });

  it('handles an empty string', () => {
    expect(snippet('')).toBe('');
  });
});

describe('readLines', () => {
  beforeEach(() => resetReadErrors());

  it('parses one JSON object per non-blank line', () => {
    const file = writeJsonl(tmp(), 'a.jsonl', [{ a: 1 }, '', { b: 2 }, '   ']);
    expect(readLines(file)).toEqual([{ a: 1 }, { b: 2 }]);
  });

  it('skips a torn trailing line without failing the whole read', () => {
    const file = path.join(tmp(), 'torn.jsonl');
    fs.writeFileSync(file, JSON.stringify({ a: 1 }) + '\n{"b":');
    expect(readLines(file)).toEqual([{ a: 1 }]);
  });

  it('returns no lines and records NO error for a missing file (routine deletion)', () => {
    expect(readLines(path.join(tmp(), 'nope.jsonl'))).toEqual([]);
    expect(getReadErrors()).toEqual([]);
  });

  it('records an unreadable file in the shared collector rather than throwing', () => {
    const dir = tmp();
    // Reading a directory as a file fails with EISDIR / EPERM, never ENOENT.
    expect(readLines(dir)).toEqual([]);
    expect(getReadErrors()).toHaveLength(1);
    expect(getReadErrors()[0].file).toBe(dir);
  });

  it('routes errors to a caller-supplied collector, leaving the shared one clean', () => {
    const mine = [];
    readLines(tmp(), mine);
    expect(mine).toHaveLength(1);
    expect(getReadErrors()).toEqual([]);
  });
});

describe('firstTimestamp', () => {
  it('returns the first timestamp found at the head of the file', () => {
    const file = writeJsonl(tmp(), 'ts.jsonl', [
      { type: 'summary' },
      { timestamp: '2026-01-02T03:04:05Z' },
      { timestamp: '2026-09-09T00:00:00Z' },
    ]);
    expect(firstTimestamp(file)).toBe('2026-01-02T03:04:05Z');
  });

  it('returns null when no line carries a timestamp', () => {
    expect(firstTimestamp(writeJsonl(tmp(), 'none.jsonl', [{ a: 1 }]))).toBeNull();
  });

  it('returns null for a missing file instead of throwing', () => {
    expect(firstTimestamp(path.join(tmp(), 'gone.jsonl'))).toBeNull();
  });

  it('gives up quietly on a line truncated by the read window', () => {
    const file = path.join(tmp(), 'big.jsonl');
    fs.writeFileSync(file, '{"a":"' + 'x'.repeat(70 * 1024));
    expect(firstTimestamp(file)).toBeNull();
  });
});
