import fs from 'node:fs';
import { SNIPPET_CHARS } from './config.js';

/**
 * 這些開頭代表該 user 行是機器產生的，不是人打的：IDE 事件、local-command 的管路、
 * 任務通知。把這些雜訊拿去排名，真正貴的 prompt 就會被埋掉。
 *
 * 斜線指令刻意「不」列在這裡。`/code-review` 是人真的做了的事，也確實花了錢：
 * 把它當雜訊會讓每個以斜線指令開頭的 session —— 本機有 15 個 —— 完全沒有可歸因的
 * prompt，導致 $63.59 的主記錄成本變成孤兒。見 commandOf()。
 */
const NOISE_PREFIXES = [
  '<local-command-caveat>',
  '<local-command-stdout>',
  '<local-command-stderr>',
  '<command-args>',
  '<task-notification>',
  '<system-reminder>',
  '<user-prompt-submit-hook>',
  '<ide_opened_file>',
  '<ide_selection>',
  '<ide_diagnostics>',
  'Caveat: The messages below were generated by the user while running local commands',
  'This session is being continued from a previous conversation',
];

/** 內容只有附件的 prompt 用這個字串代表。 */
export const ATTACHMENT_ONLY = '(附件：圖片／文件)';

/**
 * 從一個 user 行的 content 取出人類實際打的文字。
 *
 * 在這份資料裡 content 有好幾種形狀（統計自所有 main 檔案）：
 *   string             471   單純打字的 prompt
 *   array[tool_result] 4603  agent 迴圈的延續 —— 絕對不是 prompt
 *   array[text]        137   打字的 prompt，區塊形式
 *   array[image,text]  14    打字的 prompt 並貼上圖片
 *   array[image]       4     只有圖片的 prompt
 *   array[document]    1     只有文件的 prompt
 *
 * 若這行根本不是 prompt 就回傳 null。
 */
export function textOf(content) {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return null;
  if (content.some((b) => b?.type === 'tool_result')) return null;
  const text = content
    .filter((b) => b?.type === 'text' && typeof b.text === 'string')
    .map((b) => b.text)
    .join('\n');
  if (text.trim()) return text;
  // 只有附件的 prompt 也是真的，而且會產生成本；給它一個標籤，讓它的 turn 仍能被
  // 歸因，而不是掉進 __unattributed__。
  if (content.some((b) => b?.type === 'image' || b?.type === 'document')) return ATTACHMENT_ONLY;
  return null;
}

/**
 * 一份記錄裡最早的時間戳，只讀檔案開頭。
 * 用來在不完整解析的前提下，把 session 依時間排序。
 */
export function firstTimestamp(file) {
  let fd;
  try {
    fd = fs.openSync(file, 'r');
    const buf = Buffer.alloc(64 * 1024);
    const n = fs.readSync(fd, buf, 0, buf.length, 0);
    for (const line of buf.subarray(0, n).toString('utf8').split('\n')) {
      if (!line.trim()) continue;
      try {
        const j = JSON.parse(line);
        if (j.timestamp) return j.timestamp;
      } catch {
        break; // 被讀取視窗截斷了；到這裡就夠了
      }
    }
  } catch {
    // 讀不到
  } finally {
    if (fd !== undefined) fs.closeSync(fd);
  }
  return null;
}

/**
 * 自上次 resetReadErrors() 以來開不起來的記錄檔。
 *
 * 以前讀不到的記錄和空記錄完全無法區分：裡面的成本會靜默變成 $0，而且沒有任何地方
 * 會講。改成直接拋錯又更糟 —— Claude Code 正在寫入而短暫鎖住的檔案就會讓整個儀表板
 * 掛掉 —— 所以讀取失敗仍然退化成「沒有任何行」，但現在會被計數並顯示在 /api/health。
 *
 * 這個收集器只服務 ~/.claude/projects 這份語料。其他呼叫端（localagent.js）透過
 * readLines 的第二個參數傳自己的收集器進來：它們掃的是不同的根目錄、不同的時機，
 * 而它們的失敗以前會落到這裡，被當成記錄掃描失敗顯示在健康狀態卡上。
 */
let readErrors = [];
export const getReadErrors = () => readErrors;
export const resetReadErrors = () => { readErrors = []; };

export function readLines(file, errors = readErrors) {
  const out = [];
  let raw;
  try {
    raw = fs.readFileSync(file, 'utf8');
  } catch (err) {
    // ENOENT 是常態：session 可能在掃描與讀取之間被刪掉。
    if (err.code !== 'ENOENT') errors.push({ file, code: err.code ?? 'unknown' });
    return out;
  }
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    try {
      out.push(JSON.parse(line));
    } catch {
      // 進行中的 session 最後一行被截斷是正常的；跳過
    }
  }
  return out;
}

const COMMAND_NAME_RE = /<command-name>\s*([^<]*?)\s*<\/command-name>/;
const COMMAND_ARGS_RE = /<command-args>([\s\S]*?)<\/command-args>/;

/**
 * 解析出一次斜線指令的呼叫；文字不是指令時回傳 null。
 *
 * 這份資料裡有兩種線上格式（142 行）：內建指令把 `<command-name>` 放前面，而且
 * 「一定」帶 `<command-args>` 標籤；skill 與自訂指令則把 `<command-message>` 放前面，
 * 只有在使用者真的傳了參數時才帶那個標籤。
 */
function commandOf(text) {
  const m = COMMAND_NAME_RE.exec(text);
  if (!m) return null;
  const a = COMMAND_ARGS_RE.exec(text);
  return { name: m[1].trim(), args: a ? a[1].trim() : null, hasArgsTag: Boolean(a) };
}

/**
 * 這一行是不是人真的打出來的 prompt —— 或是他呼叫的斜線指令。對我們來說兩者是同一件事：
 * 都是使用者刻意做出、且會花錢的動作。
 *
 * `hasArgsTag && !args` 這條規則是用「結構」把無作用的設定類指令（/clear、/effort、
 * /agents、/upgrade、/login）濾掉，而不是靠一份會隨 Claude Code 新增指令而過期的名單。
 * 這些 turn 在本機的成本都是 $0.00，所以這是排名決策而非記帳決策；最壞的情況是未來某個
 * 不帶參數卻真的會做事的指令被併進前一個 prompt，而不是變成無法歸因。
 * `/model claude-fable-5` 帶參數所以會留下來 —— 這是刻意的，它是真實動作，而且依成本
 * 排序後它自然會沉到最底下。
 *
 * 刻意「不」使用 `promptSource` —— 實測在這份資料上不可靠（`sdk` 同時涵蓋人類與機器
 * 的 prompt；470 行裡只有 2 行是 `typed`）。
 */
export function isRealPrompt(line) {
  if (line?.type !== 'user') return false;
  if (line.isMeta === true) return false;
  if (line.isSidechain === true) return false; // 屬於某個 agent 自己的迴圈
  const raw = textOf(line.message?.content);
  if (!raw) return false;
  const t = raw.trim();
  if (!t) return false;
  if (t.startsWith('<command-name>') || t.startsWith('<command-message>')) {
    const cmd = commandOf(t);
    if (!cmd) return false; // 格式壞掉的管路，一樣是雜訊
    return !(cmd.hasArgsTag && !cmd.args);
  }
  return !NOISE_PREFIXES.some((p) => t.startsWith(p));
}

/**
 * 取出一個已確定通過 isRealPrompt() 的行的 prompt 文字。
 * 指令會呈現成 `/code-review` 或 `/goal 增加字體縮放`，絕不會是原始的 XML 區塊 ——
 * snippet() 以及每個顯示它的 UI 都直接受惠。
 */
export function promptTextOf(line) {
  const t = (textOf(line.message?.content) ?? '').trim();
  const cmd = commandOf(t);
  if (!cmd) return t;
  return cmd.args ? `${cmd.name} ${cmd.args}` : cmd.name;
}

/** 帶有可計費 usage 的 assistant 行。 */
export function isBillable(line) {
  if (line?.type !== 'assistant') return false;
  const model = line.message?.model;
  if (!model || model === '<synthetic>') return false;
  return line.message?.usage != null;
}

/**
 * 去重用的鍵。已驗證必要：ced37f19 的主記錄有 732 行可計費，但只有 249 則不重複的
 * 訊息（66% 是重複）。正是靠這個鍵去重，我們的總額才能和 ccusage 完全一致。
 */
export function dedupKey(line) {
  const id = line.message?.id;
  const rid = line.requestId;
  return id && rid ? `${id}|${rid}` : `uuid:${line.uuid}`;
}

/**
 * key -> 同一個檔案內該訊息「最後」的 usage 記錄。
 *
 * 串流中的 assistant 訊息每寫一次部分內容就會被追加一行：id|requestId 相同，
 * output_tokens 隨每次寫入增加（[3, 3, 276] 是典型值；本語料有 1307 組，每組都是遞增）。
 * 只有最後一次寫入是完整的，而 ccusage 算的也是那一次 —— 我們原本取第一次，
 * 導致全域總額少報 1.05%。
 *
 * 這裡只回傳 usage；呼叫端仍然採計「第一次」出現的位置，好讓決定成本歸屬到哪個 turn
 * 的 parentUuid 鏈保持完整。
 */
export function finalUsageByKey(lines) {
  const out = new Map();
  for (const line of lines) if (isBillable(line)) out.set(dedupKey(line), line.message.usage);
  return out;
}

export function snippet(text, n = SNIPPET_CHARS) {
  const flat = text.replace(/\s+/g, ' ').trim();
  return flat.length <= n ? flat : `${flat.slice(0, n)}…`;
}

export const _internal = { NOISE_PREFIXES };
