import fs from 'node:fs';
import { SNIPPET_CHARS } from './config.js';

/**
 * Prefixes that mark a user line as machine-generated rather than something the
 * human typed. Measured across all 74 main transcripts: of 551 user lines with
 * extractable text, only 360 are real prompts — the rest are IDE events, slash
 * command plumbing, and task notifications. Ranking that noise would bury the
 * actual expensive prompts.
 */
const NOISE_PREFIXES = [
  '<local-command-caveat>',
  '<local-command-stdout>',
  '<local-command-stderr>',
  '<command-name>',
  '<command-message>',
  '<command-args>',
  '<task-notification>',
  '<system-reminder>',
  '<user-prompt-submit-hook>',
  '<ide_opened_file>',
  '<ide_selection>',
  '<ide_diagnostics>',
  'Caveat: The messages below were generated by the user while running local commands',
  'This session is being continued from a previous conversation',
];

/** Placeholder for a prompt whose only content is an attachment. */
export const ATTACHMENT_ONLY = '(附件：圖片／文件)';

/**
 * Extract the human-typed text from a user line's content.
 *
 * Content comes in several shapes on this data (counts across all main files):
 *   string             471   plain typed prompt
 *   array[tool_result] 4603  agent-loop continuation — never a prompt
 *   array[text]        137   typed prompt, block form
 *   array[image,text]  14    typed prompt with a pasted image
 *   array[image]       4     image-only prompt
 *   array[document]    1     document-only prompt
 *
 * Returns null when the line is not a prompt at all.
 */
export function textOf(content) {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return null;
  if (content.some((b) => b?.type === 'tool_result')) return null;
  const text = content
    .filter((b) => b?.type === 'text' && typeof b.text === 'string')
    .map((b) => b.text)
    .join('\n');
  if (text.trim()) return text;
  // Attachment-only prompts are real and carry cost; give them a label so their
  // turn still gets attributed instead of falling into __unattributed__.
  if (content.some((b) => b?.type === 'image' || b?.type === 'document')) return ATTACHMENT_ONLY;
  return null;
}

/**
 * Earliest timestamp in a transcript, read from the head of the file only.
 * Used to order sessions chronologically without parsing them in full.
 */
export function firstTimestamp(file) {
  let fd;
  try {
    fd = fs.openSync(file, 'r');
    const buf = Buffer.alloc(64 * 1024);
    const n = fs.readSync(fd, buf, 0, buf.length, 0);
    for (const line of buf.subarray(0, n).toString('utf8').split('\n')) {
      if (!line.trim()) continue;
      try {
        const j = JSON.parse(line);
        if (j.timestamp) return j.timestamp;
      } catch {
        break; // truncated by the read window; good enough
      }
    }
  } catch {
    // unreadable
  } finally {
    if (fd !== undefined) fs.closeSync(fd);
  }
  return null;
}

export function readLines(file) {
  const out = [];
  let raw;
  try {
    raw = fs.readFileSync(file, 'utf8');
  } catch {
    return out;
  }
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    try {
      out.push(JSON.parse(line));
    } catch {
      // a torn last line on a live session is expected; skip it
    }
  }
  return out;
}

/**
 * True when this line is a prompt a human actually typed.
 *
 * Deliberately does NOT use `promptSource` — verified unreliable on this data
 * (`sdk` covers both human and machine prompts; only 2 of 470 lines were `typed`).
 */
export function isRealPrompt(line) {
  if (line?.type !== 'user') return false;
  if (line.isMeta === true) return false;
  if (line.isSidechain === true) return false; // belongs to an agent's own loop
  const raw = textOf(line.message?.content);
  if (!raw) return false;
  const t = raw.trim();
  if (!t) return false;
  return !NOISE_PREFIXES.some((p) => t.startsWith(p));
}

/** The prompt text of a line already known to satisfy isRealPrompt(). */
export function promptTextOf(line) {
  return (textOf(line.message?.content) ?? '').trim();
}

/** An assistant line that carries billable usage. */
export function isBillable(line) {
  if (line?.type !== 'assistant') return false;
  const model = line.message?.model;
  if (!model || model === '<synthetic>') return false;
  return line.message?.usage != null;
}

/**
 * Dedup key. Verified necessary: the main transcript for ced37f19 holds 732
 * billable lines but only 249 unique messages (66% repeats). Deduping on this
 * key is what makes our totals match ccusage exactly.
 */
export function dedupKey(line) {
  const id = line.message?.id;
  const rid = line.requestId;
  return id && rid ? `${id}|${rid}` : `uuid:${line.uuid}`;
}

export function snippet(text, n = SNIPPET_CHARS) {
  const flat = text.replace(/\s+/g, ' ').trim();
  return flat.length <= n ? flat : `${flat.slice(0, n)}…`;
}

export const _internal = { NOISE_PREFIXES };
