import fs from 'node:fs';
import { SNIPPET_CHARS } from './config.js';

/**
 * Prefixes that mark a user line as machine-generated rather than something the
 * human typed: IDE events, local-command plumbing, task notifications. Ranking
 * that noise would bury the actual expensive prompts.
 *
 * A slash-command invocation is NOT on this list, deliberately. `/code-review`
 * is a real thing a human did, and it owns real spend: treating it as noise left
 * every session that opened with one — 15 of them here — with no attributable
 * prompt at all, orphaning $63.59 of main-transcript cost. See commandOf().
 */
const NOISE_PREFIXES = [
  '<local-command-caveat>',
  '<local-command-stdout>',
  '<local-command-stderr>',
  '<command-args>',
  '<task-notification>',
  '<system-reminder>',
  '<user-prompt-submit-hook>',
  '<ide_opened_file>',
  '<ide_selection>',
  '<ide_diagnostics>',
  'Caveat: The messages below were generated by the user while running local commands',
  'This session is being continued from a previous conversation',
];

/** Placeholder for a prompt whose only content is an attachment. */
export const ATTACHMENT_ONLY = '(附件：圖片／文件)';

/**
 * Extract the human-typed text from a user line's content.
 *
 * Content comes in several shapes on this data (counts across all main files):
 *   string             471   plain typed prompt
 *   array[tool_result] 4603  agent-loop continuation — never a prompt
 *   array[text]        137   typed prompt, block form
 *   array[image,text]  14    typed prompt with a pasted image
 *   array[image]       4     image-only prompt
 *   array[document]    1     document-only prompt
 *
 * Returns null when the line is not a prompt at all.
 */
export function textOf(content) {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return null;
  if (content.some((b) => b?.type === 'tool_result')) return null;
  const text = content
    .filter((b) => b?.type === 'text' && typeof b.text === 'string')
    .map((b) => b.text)
    .join('\n');
  if (text.trim()) return text;
  // Attachment-only prompts are real and carry cost; give them a label so their
  // turn still gets attributed instead of falling into __unattributed__.
  if (content.some((b) => b?.type === 'image' || b?.type === 'document')) return ATTACHMENT_ONLY;
  return null;
}

/**
 * Earliest timestamp in a transcript, read from the head of the file only.
 * Used to order sessions chronologically without parsing them in full.
 */
export function firstTimestamp(file) {
  let fd;
  try {
    fd = fs.openSync(file, 'r');
    const buf = Buffer.alloc(64 * 1024);
    const n = fs.readSync(fd, buf, 0, buf.length, 0);
    for (const line of buf.subarray(0, n).toString('utf8').split('\n')) {
      if (!line.trim()) continue;
      try {
        const j = JSON.parse(line);
        if (j.timestamp) return j.timestamp;
      } catch {
        break; // truncated by the read window; good enough
      }
    }
  } catch {
    // unreadable
  } finally {
    if (fd !== undefined) fs.closeSync(fd);
  }
  return null;
}

/**
 * Transcripts we could not open, since the last resetReadErrors().
 *
 * An unreadable transcript used to be indistinguishable from an empty one: the
 * cost in it silently became $0 and nothing anywhere said so. Throwing instead
 * would be worse — a file briefly locked while Claude Code writes it would take
 * the whole dashboard down — so the read still degrades to "no lines", but it
 * is now counted and surfaced in /api/health.
 *
 * This is the collector for the ~/.claude/projects corpus only. Other callers
 * (localagent.js) pass their own via readLines' second argument: they scan a
 * different root on a different schedule, and their failures used to land here
 * and get reported as a transcript-scan failure on the health card.
 */
let readErrors = [];
export const getReadErrors = () => readErrors;
export const resetReadErrors = () => { readErrors = []; };

export function readLines(file, errors = readErrors) {
  const out = [];
  let raw;
  try {
    raw = fs.readFileSync(file, 'utf8');
  } catch (err) {
    // ENOENT is routine: a session can be deleted between the scan and the read.
    if (err.code !== 'ENOENT') errors.push({ file, code: err.code ?? 'unknown' });
    return out;
  }
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    try {
      out.push(JSON.parse(line));
    } catch {
      // a torn last line on a live session is expected; skip it
    }
  }
  return out;
}

const COMMAND_NAME_RE = /<command-name>\s*([^<]*?)\s*<\/command-name>/;
const COMMAND_ARGS_RE = /<command-args>([\s\S]*?)<\/command-args>/;

/**
 * A slash-command invocation, or null when the text is not one.
 *
 * Two wire shapes on this data (142 lines): built-in commands put
 * `<command-name>` first and ALWAYS carry a `<command-args>` tag; skill and
 * custom commands put `<command-message>` first and carry the tag only when the
 * user actually passed arguments.
 */
function commandOf(text) {
  const m = COMMAND_NAME_RE.exec(text);
  if (!m) return null;
  const a = COMMAND_ARGS_RE.exec(text);
  return { name: m[1].trim(), args: a ? a[1].trim() : null, hasArgsTag: Boolean(a) };
}

/**
 * True when this line is a prompt a human actually typed — or a slash command
 * they invoked, which is the same thing for our purposes: a deliberate user
 * action that causes spend.
 *
 * The `hasArgsTag && !args` rule drops no-op settings commands (/clear, /effort,
 * /agents, /upgrade, /login) structurally, rather than via a name list that goes
 * stale as Claude Code adds commands. Every one of those turns costs $0.00 here,
 * so it is a ranking decision, not an accounting one; worst case a future no-arg
 * command that does real work gets folded into the preceding prompt rather than
 * becoming unattributable. `/model claude-fable-5` carries args and so survives —
 * that is intended, it is a real action, and cost-sorting sinks it to the bottom.
 *
 * Deliberately does NOT use `promptSource` — verified unreliable on this data
 * (`sdk` covers both human and machine prompts; only 2 of 470 lines were `typed`).
 */
export function isRealPrompt(line) {
  if (line?.type !== 'user') return false;
  if (line.isMeta === true) return false;
  if (line.isSidechain === true) return false; // belongs to an agent's own loop
  const raw = textOf(line.message?.content);
  if (!raw) return false;
  const t = raw.trim();
  if (!t) return false;
  if (t.startsWith('<command-name>') || t.startsWith('<command-message>')) {
    const cmd = commandOf(t);
    if (!cmd) return false; // malformed plumbing, still noise
    return !(cmd.hasArgsTag && !cmd.args);
  }
  return !NOISE_PREFIXES.some((p) => t.startsWith(p));
}

/**
 * The prompt text of a line already known to satisfy isRealPrompt().
 * A command renders as `/code-review` or `/goal 增加字體縮放`, never as the raw
 * XML blob — snippet() and every UI that shows it inherit this for free.
 */
export function promptTextOf(line) {
  const t = (textOf(line.message?.content) ?? '').trim();
  const cmd = commandOf(t);
  if (!cmd) return t;
  return cmd.args ? `${cmd.name} ${cmd.args}` : cmd.name;
}

/** An assistant line that carries billable usage. */
export function isBillable(line) {
  if (line?.type !== 'assistant') return false;
  const model = line.message?.model;
  if (!model || model === '<synthetic>') return false;
  return line.message?.usage != null;
}

/**
 * Dedup key. Verified necessary: the main transcript for ced37f19 holds 732
 * billable lines but only 249 unique messages (66% repeats). Deduping on this
 * key is what makes our totals match ccusage exactly.
 */
export function dedupKey(line) {
  const id = line.message?.id;
  const rid = line.requestId;
  return id && rid ? `${id}|${rid}` : `uuid:${line.uuid}`;
}

/**
 * key -> the FINAL usage record for that message within one file.
 *
 * A streamed assistant message is appended once per partial write: same
 * id|requestId, output_tokens growing with each write ([3, 3, 276] is typical;
 * 1307 such groups on this corpus, every one monotonic). Only the last write is
 * complete, and it is the one ccusage counts — taking the first, as we did,
 * under-reported the global total by 1.05%.
 *
 * Returns usage only; the caller still counts the FIRST occurrence so the
 * parentUuid chain that assigns cost to a turn stays intact.
 */
export function finalUsageByKey(lines) {
  const out = new Map();
  for (const line of lines) if (isBillable(line)) out.set(dedupKey(line), line.message.usage);
  return out;
}

export function snippet(text, n = SNIPPET_CHARS) {
  const flat = text.replace(/\s+/g, ' ').trim();
  return flat.length <= n ? flat : `${flat.slice(0, n)}…`;
}

export const _internal = { NOISE_PREFIXES };
